apply-env:
	direnv allow

# Terraformプロジェクトを初期化
# プロジェクトのセットアップ時に一度だけ実行する
# プロバイダプラグインをダウンロードする
tf-init:
	terraform init

# terraform planコマンドは、Terraformが何を行うかをプレビュー
tf-plan:
	terraform plan

# 実際にリソースを作成
tf-apply:
	terraform apply